// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4nEWfxakgY8JngHqE1nyT3
// Component: 52U8BnjZZsPu
import * as React from "react";
import Link from "next/link";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: YWPWm_cPIbY/component
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: 4nEWfxakgY8JngHqE1nyT3/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: 52U8BnjZZsPu/css
import Xmlid4StrokeIcon from "./icons/PlasmicIcon__Xmlid4Stroke"; // plasmic-import: Vj4JWvt5jH/icon
import Group1Icon from "./icons/PlasmicIcon__Group1"; // plasmic-import: pmx_beGUOQ/icon

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

function PlasmicHomepage__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;
  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"figmaPaste"}
            data-plasmic-override={overrides.figmaPaste}
            className={classNames(projectcss.all, sty.figmaPaste)}
          >
            <div
              data-plasmic-name={"stilu10Pt100"}
              data-plasmic-override={overrides.stilu10Pt100}
              className={classNames(projectcss.all, sty.stilu10Pt100)}
            >
              <div
                data-plasmic-name={"group2"}
                data-plasmic-override={overrides.group2}
                className={classNames(projectcss.all, sty.group2)}
              >
                <Xmlid4StrokeIcon
                  className={classNames(projectcss.all, sty.svg__sTgZ)}
                  role={"img"}
                />

                <Group1Icon
                  className={classNames(projectcss.all, sty.svg__dIsH8)}
                  role={"img"}
                />
              </div>
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ajqwm
              )}
            >
              {"️"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__cu39H
              )}
            >
              {"Made With ❤ in Athens"}
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__ldDdt
              )}
            >
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ color: "#282E4D" }}
                >
                  {"We Deliver"}
                </span>
                <React.Fragment> </React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ color: "#3C5BFF" }}
                >
                  {".Value"}
                </span>
                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </div>

            <div
              data-plasmic-name={"group6"}
              data-plasmic-override={overrides.group6}
              className={classNames(projectcss.all, sty.group6)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ij87D
                )}
              >
                {"About"}
              </div>
            </div>

            <div
              data-plasmic-name={"group7"}
              data-plasmic-override={overrides.group7}
              className={classNames(projectcss.all, sty.group7)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__qIZxA
                )}
              >
                {"Tools & Calculators"}
              </div>
            </div>

            <div
              data-plasmic-name={"group8"}
              data-plasmic-override={overrides.group8}
              className={classNames(projectcss.all, sty.group8)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__l40Tn
                )}
              >
                {"Tracking Library"}
              </div>
            </div>

            <div
              data-plasmic-name={"group9"}
              data-plasmic-override={overrides.group9}
              className={classNames(projectcss.all, sty.group9)}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__yw9TP
                )}
              >
                {"Services"}
              </div>
            </div>

            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__xF5Fl
              )}
            >
              <React.Fragment>
                <React.Fragment>{""}</React.Fragment>
                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    projectcss.plasmic_default__inline,
                    sty.link__z3M8
                  )}
                  component={Link}
                  href={"fd"}
                  platform={"nextjs"}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#282E4D" }}
                    >
                      {"GTM Tags"}
                    </span>
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </p.PlasmicLink>
                <React.Fragment>{""}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ color: "#282E4D" }}
                >
                  {", "}
                </span>
                <React.Fragment>{""}</React.Fragment>
                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    projectcss.plasmic_default__inline,
                    sty.link__trIgP
                  )}
                  component={Link}
                  href={"ggd"}
                  platform={"nextjs"}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#4162FF" }}
                    >
                      {"Marketing Calculators"}
                    </span>
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </p.PlasmicLink>
                <React.Fragment>{""}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ color: "#282E4D" }}
                >
                  {" "}
                </span>
                <React.Fragment>{"\n"}</React.Fragment>
                <span
                  className={"plasmic_default__all plasmic_default__span"}
                  style={{ color: "#282E4D" }}
                >
                  {"and "}
                </span>
                <React.Fragment>{""}</React.Fragment>
                <p.PlasmicLink
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    projectcss.__wab_text,
                    projectcss.plasmic_default__inline,
                    sty.link__o3Vki
                  )}
                  component={Link}
                  href={"fd"}
                  platform={"nextjs"}
                >
                  <React.Fragment>
                    <React.Fragment>{""}</React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ color: "#282E4D" }}
                    >
                      {"Javascript Fun."}
                    </span>
                    <React.Fragment>{""}</React.Fragment>
                  </React.Fragment>
                </p.PlasmicLink>
                <React.Fragment>{""}</React.Fragment>
              </React.Fragment>
            </div>

            <Button
              data-plasmic-name={"checkServices"}
              data-plasmic-override={overrides.checkServices}
              className={classNames("__wab_instance", sty.checkServices)}
              color={"blue"}
            >
              {" ✌ Check Services"}
            </Button>
          </div>
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "figmaPaste",
    "stilu10Pt100",
    "group2",
    "group6",
    "group7",
    "group8",
    "group9",
    "checkServices"
  ],

  figmaPaste: [
    "figmaPaste",
    "stilu10Pt100",
    "group2",
    "group6",
    "group7",
    "group8",
    "group9",
    "checkServices"
  ],

  stilu10Pt100: ["stilu10Pt100", "group2"],
  group2: ["group2"],
  group6: ["group6"],
  group7: ["group7"],
  group8: ["group8"],
  group9: ["group9"],
  checkServices: ["checkServices"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    figmaPaste: makeNodeComponent("figmaPaste"),
    stilu10Pt100: makeNodeComponent("stilu10Pt100"),
    group2: makeNodeComponent("group2"),
    group6: makeNodeComponent("group6"),
    group7: makeNodeComponent("group7"),
    group8: makeNodeComponent("group8"),
    group9: makeNodeComponent("group9"),
    checkServices: makeNodeComponent("checkServices"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
